### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by dariuszpiwowarski**

### CODE REVIEW

**Comment by dariuszpiwowarski** [comment]
I think it's a typo, but I'm not a native, so..

**Comment by kgiszczak** [comment]
Thanks Dariusz for your PR, I much appreciate it. I'm not a native myself but I believe it should be "contents" as in "table of contents", look here for example: https://getproofed.com/writing-tips/word-choice-content-vs-contents/#:~:text=Content%20is%20an%20uncountable%20noun,%E2%80%9Ctable%20of%20contents%E2%80%9D).

**Comment by kgiszczak** [comment]
Thanks Dariusz for your PR, I much appreciate it. I'm not a native myself but I believe it should be "contents" and in "table of contents", look here for example: https://getproofed.com/writing-tips/word-choice-content-vs-contents/#:~:text=Content%20is%20an%20uncountable%20noun,%E2%80%9Ctable%20of%20contents%E2%80%9D).

**Comment by dariuszpiwowarski** [comment]
Wow. Learned something new.

**Pull request closed without merging**
